name: Quality checks
on: push
permissions:
  contents: read
  pull-requests: read
  packages: read
jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      GH_API_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install modules
        run: npm ci
      - name: eslint
        run: npm run lint
      - name: prettier
        run: npm run format:check
  Unit-tests:
    runs-on: ubuntu-latest
    env:
      GH_API_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install modules
        run: npm ci
      - name: Unit tests
        run: npm run test:coverage
      - name: Upload Coverage
        uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4.4.2
        with:
          name: jest
          path: coverage/lcov.info
      - name: Unit tests
        run: cp coverage/lcov.info coverage/lcov-report/unit-lcov.info

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs:
      - Unit-tests
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Download Coverage Results
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@eb211723266fe8e83102bac7361f0a05c3ac1d1b # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
